TEXT_WIN  = "KAZANDI";
TEXT_CONGRATS = "TEBRİKLER!";
TEXT_NO_WIN    = "KAYBETTİNİZ";
TEXT_PLAY      = "OYNA";
TEXT_HELP1     = "GRİ BÖLÜMLERİ KAZIYINIZ. 3 ADET YANYANA AYNI SEMBOL ÇIKARSA, ÖDÜLÜ KAZANIRSINIZ!!";

TEXT_HEAD       = "ÖDÜLLERİ KAZAN!";
TEXT_CURRENCY  = "₺";
TEXT_SCORE     = "PARA";
TEXT_ADVICE_WIN = "KAZANDI";
TEXT_ADVICE_LOSE = "KAZANAMADI";

TEXT_CREDIT = "PARA";
TEXT_PLUS = "+";
TEXT_MINUS = "-";
TEXT_BUYCARD = "SATIN AL";
TEXT_WIN_AMOUNT = "TOPLAM KAZANÇ";
TEXT_CARD_VALUE = "YATIR";
TEXT_PLAY_AGAIN = "TEKRAR";

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better?";