TEXT_GAMEOVER  = "OYUN BİTTİ";
TEXT_CONGRATS  = "TEBRİKLER";
TEXT_MONEY     = "PARA";
TEXT_PLAY      = "OYNA";
TEXT_BET       = "YATIR";
TEXT_COIN      = "JETON";
TEXT_MAX_BET   = "MAX YATIR";
TEXT_INFO      = "BİLGİ";
TEXT_LINES     = "SATIR";
TEXT_SPIN      = "DÖNDÜR";
TEXT_WIN       = "KAZANDINIZ";
TEXT_HELP_WILD = "HER SEMBÖLÜN YERİNE GEÇEREK COMBO YAPABİLEN SEMBOLDÜR";

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Tebrikler!";
TEXT_SHARE_MSG1 = "Kazandınız <strong>";
TEXT_SHARE_MSG2 = " puan </strong>!<br><br>Puanını arkadaşlarınla paylaş";
TEXT_SHARE_SHARE1 = "Puanım ";
TEXT_SHARE_SHARE2 = " puan! Daha iyisini yapabilirmisin?";